### ISSUE TITLE
Fuzzing Strategies Syntax

### ISSUE THREAD

**Issue by LucaBongiorni** [CERTCC/certfuzz#13]
Hi,
I am trying to understand how to properly define the range_list parameter in order to fuzz only a certain bytes offset of the seedfiles.

In the README is mentioned that the bytes range should be one per line (in HEX or DECIMAL).
`range_list: byte ranges to be fuzzed. One range per line, hex or decimal`

My idea is too instruct BFF to fuzz only the first 30KB of each seedfile.
Therefore should I place something like this in the BFF.yaml?

```
##############################################################################
fuzzer:
    fuzzer: bytemut
    fuzz_zip_container: False
    range_list: 0x0000
    range_list: 0x7530

```

Or should I use min_ratio & max_ratio as mentioned in bytemut.py? (which looks like the option, to instruct BFF how many bytes fuzz at the same time for each iteration)

```
class ByteMutFuzzer(MinimizableFuzzer):
    '''
    This fuzzer module randomly selects bytes in an input file and assigns
    them random values. The percent of the selected bytes can be tweaked by
    min_ratio and max_ratio. range_list specifies a range in the file to fuzz.
    Roughly similar to cmiller's 5 lines o' python, except clearly less space
    efficient.
    '''
```
